# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swimprotocol/grpc/swimprotocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='swimprotocol/grpc/swimprotocol.proto',
  package='swimprotocol.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$swimprotocol/grpc/swimprotocol.proto\x12\x11swimprotocol.grpc\"\x06\n\x04Ping\"\x19\n\x07PingReq\x12\x0e\n\x06target\x18\x03 \x01(\t\"H\n\x03\x41\x63k\x12-\n\x07\x66\x61ilure\x18\x01 \x01(\x0b\x32\x1a.swimprotocol.grpc.FailureH\x00\x42\x12\n\x10optional_failure\"G\n\x07\x46\x61ilure\x12\r\n\x03key\x18\x01 \x01(\tH\x00\x12\r\n\x03msg\x18\x02 \x01(\tH\x01\x42\x0e\n\x0coptional_keyB\x0e\n\x0coptional_msg\"\xbf\x01\n\x06Update\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05\x63lock\x18\x02 \x01(\x04\x12)\n\x06status\x18\x03 \x01(\x0e\x32\x19.swimprotocol.grpc.Status\x12\x39\n\x08metadata\x18\x04 \x03(\x0b\x32\'.swimprotocol.grpc.Update.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x06Gossip\x12\x0e\n\x06source\x18\x01 \x01(\t\x12*\n\x07updates\x18\x02 \x03(\x0b\x32\x19.swimprotocol.grpc.Update*\x1a\n\x06Status\x12\x08\n\x04\x44OWN\x10\x00\x12\x06\n\x02UP\x10\x01\x32\xdf\x01\n\x0cSwimProtocol\x12@\n\x0bPingCommand\x12\x17.swimprotocol.grpc.Ping\x1a\x16.swimprotocol.grpc.Ack\"\x00\x12\x46\n\x0ePingReqCommand\x12\x1a.swimprotocol.grpc.PingReq\x1a\x16.swimprotocol.grpc.Ack\"\x00\x12\x45\n\x0bSyncCommand\x12\x19.swimprotocol.grpc.Gossip\x1a\x19.swimprotocol.grpc.Gossip\"\x00\x62\x06proto3'
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='swimprotocol.grpc.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=505,
  serialized_end=531,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
DOWN = 0
UP = 1



_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='swimprotocol.grpc.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=65,
)


_PINGREQ = _descriptor.Descriptor(
  name='PingReq',
  full_name='swimprotocol.grpc.PingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='swimprotocol.grpc.PingReq.target', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=92,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='swimprotocol.grpc.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='failure', full_name='swimprotocol.grpc.Ack.failure', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_failure', full_name='swimprotocol.grpc.Ack.optional_failure',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=94,
  serialized_end=166,
)


_FAILURE = _descriptor.Descriptor(
  name='Failure',
  full_name='swimprotocol.grpc.Failure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='swimprotocol.grpc.Failure.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='swimprotocol.grpc.Failure.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_key', full_name='swimprotocol.grpc.Failure.optional_key',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_msg', full_name='swimprotocol.grpc.Failure.optional_msg',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=168,
  serialized_end=239,
)


_UPDATE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='swimprotocol.grpc.Update.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='swimprotocol.grpc.Update.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='swimprotocol.grpc.Update.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=433,
)

_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='swimprotocol.grpc.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='swimprotocol.grpc.Update.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='swimprotocol.grpc.Update.clock', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='swimprotocol.grpc.Update.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='swimprotocol.grpc.Update.metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_UPDATE_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=433,
)


_GOSSIP = _descriptor.Descriptor(
  name='Gossip',
  full_name='swimprotocol.grpc.Gossip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='swimprotocol.grpc.Gossip.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updates', full_name='swimprotocol.grpc.Gossip.updates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=503,
)

_ACK.fields_by_name['failure'].message_type = _FAILURE
_ACK.oneofs_by_name['optional_failure'].fields.append(
  _ACK.fields_by_name['failure'])
_ACK.fields_by_name['failure'].containing_oneof = _ACK.oneofs_by_name['optional_failure']
_FAILURE.oneofs_by_name['optional_key'].fields.append(
  _FAILURE.fields_by_name['key'])
_FAILURE.fields_by_name['key'].containing_oneof = _FAILURE.oneofs_by_name['optional_key']
_FAILURE.oneofs_by_name['optional_msg'].fields.append(
  _FAILURE.fields_by_name['msg'])
_FAILURE.fields_by_name['msg'].containing_oneof = _FAILURE.oneofs_by_name['optional_msg']
_UPDATE_METADATAENTRY.containing_type = _UPDATE
_UPDATE.fields_by_name['status'].enum_type = _STATUS
_UPDATE.fields_by_name['metadata'].message_type = _UPDATE_METADATAENTRY
_GOSSIP.fields_by_name['updates'].message_type = _UPDATE
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['PingReq'] = _PINGREQ
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
DESCRIPTOR.message_types_by_name['Failure'] = _FAILURE
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
DESCRIPTOR.message_types_by_name['Gossip'] = _GOSSIP
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'swimprotocol.grpc.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.Ping)
  })
_sym_db.RegisterMessage(Ping)

PingReq = _reflection.GeneratedProtocolMessageType('PingReq', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQ,
  '__module__' : 'swimprotocol.grpc.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.PingReq)
  })
_sym_db.RegisterMessage(PingReq)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'swimprotocol.grpc.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.Ack)
  })
_sym_db.RegisterMessage(Ack)

Failure = _reflection.GeneratedProtocolMessageType('Failure', (_message.Message,), {
  'DESCRIPTOR' : _FAILURE,
  '__module__' : 'swimprotocol.grpc.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.Failure)
  })
_sym_db.RegisterMessage(Failure)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _UPDATE_METADATAENTRY,
    '__module__' : 'swimprotocol.grpc.swimprotocol_pb2'
    # @@protoc_insertion_point(class_scope:swimprotocol.grpc.Update.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'swimprotocol.grpc.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.Update)
  })
_sym_db.RegisterMessage(Update)
_sym_db.RegisterMessage(Update.MetadataEntry)

Gossip = _reflection.GeneratedProtocolMessageType('Gossip', (_message.Message,), {
  'DESCRIPTOR' : _GOSSIP,
  '__module__' : 'swimprotocol.grpc.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.Gossip)
  })
_sym_db.RegisterMessage(Gossip)


_UPDATE_METADATAENTRY._options = None

_SWIMPROTOCOL = _descriptor.ServiceDescriptor(
  name='SwimProtocol',
  full_name='swimprotocol.grpc.SwimProtocol',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=534,
  serialized_end=757,
  methods=[
  _descriptor.MethodDescriptor(
    name='PingCommand',
    full_name='swimprotocol.grpc.SwimProtocol.PingCommand',
    index=0,
    containing_service=None,
    input_type=_PING,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PingReqCommand',
    full_name='swimprotocol.grpc.SwimProtocol.PingReqCommand',
    index=1,
    containing_service=None,
    input_type=_PINGREQ,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SyncCommand',
    full_name='swimprotocol.grpc.SwimProtocol.SyncCommand',
    index=2,
    containing_service=None,
    input_type=_GOSSIP,
    output_type=_GOSSIP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SWIMPROTOCOL)

DESCRIPTOR.services_by_name['SwimProtocol'] = _SWIMPROTOCOL

# @@protoc_insertion_point(module_scope)
