"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___Status = Status
class _Status(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Status.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    OFFLINE = Status.V(0)
    ONLINE = Status.V(1)
class Status(metaclass=_Status):
    V = typing.NewType('V', builtins.int)
OFFLINE = Status.V(0)
ONLINE = Status.V(1)

class Ping(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___Ping = Ping

class PingReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TARGET_FIELD_NUMBER: builtins.int
    target: typing.Text = ...

    def __init__(self,
        *,
        target : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"target",b"target"]) -> None: ...
global___PingReq = PingReq

class Ack(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FAILURE_FIELD_NUMBER: builtins.int

    @property
    def failure(self) -> global___Failure: ...

    def __init__(self,
        *,
        failure : typing.Optional[global___Failure] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"failure",b"failure",u"optional_failure",b"optional_failure"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"failure",b"failure",u"optional_failure",b"optional_failure"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"optional_failure",b"optional_failure"]) -> typing_extensions.Literal["failure"]: ...
global___Ack = Ack

class Failure(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    key: typing.Text = ...
    msg: typing.Text = ...

    def __init__(self,
        *,
        key : typing.Text = ...,
        msg : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"key",b"key",u"msg",b"msg",u"optional_key",b"optional_key",u"optional_msg",b"optional_msg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"msg",b"msg",u"optional_key",b"optional_key",u"optional_msg",b"optional_msg"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"optional_key",b"optional_key"]) -> typing_extensions.Literal["key"]: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal[u"optional_msg",b"optional_msg"]) -> typing_extensions.Literal["msg"]: ...
global___Failure = Failure

class Update(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: typing.Text = ...

        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    ADDRESS_FIELD_NUMBER: builtins.int
    CLOCK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    address: typing.Text = ...
    clock: builtins.int = ...
    status: global___Status.V = ...

    @property
    def metadata(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...

    def __init__(self,
        *,
        address : typing.Text = ...,
        clock : builtins.int = ...,
        status : global___Status.V = ...,
        metadata : typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"address",b"address",u"clock",b"clock",u"metadata",b"metadata",u"status",b"status"]) -> None: ...
global___Update = Update

class Gossip(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SOURCE_FIELD_NUMBER: builtins.int
    UPDATES_FIELD_NUMBER: builtins.int
    source: typing.Text = ...

    @property
    def updates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Update]: ...

    def __init__(self,
        *,
        source : typing.Text = ...,
        updates : typing.Optional[typing.Iterable[global___Update]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"source",b"source",u"updates",b"updates"]) -> None: ...
global___Gossip = Gossip
