# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: swimprotocol/grpc/proto/swimprotocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='swimprotocol/grpc/proto/swimprotocol.proto',
  package='swimprotocol.grpc.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*swimprotocol/grpc/proto/swimprotocol.proto\x12\x17swimprotocol.grpc.proto\"\n\n\x08SwimPing\"\x1d\n\x0bSwimPingReq\x12\x0e\n\x06target\x18\x03 \x01(\t\"\x19\n\x07SwimAck\x12\x0e\n\x06online\x18\x01 \x01(\x08\"\xf1\x01\n\nSwimUpdate\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x12\n\x08modified\x18\x02 \x01(\x04H\x00\x12\x33\n\x06status\x18\x03 \x01(\x0e\x32#.swimprotocol.grpc.proto.SwimStatus\x12\x43\n\x08metadata\x18\x04 \x03(\x0b\x32\x31.swimprotocol.grpc.proto.SwimUpdate.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x13\n\x11optional_modified\"a\n\nSwimGossip\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05\x63lock\x18\x02 \x01(\x04\x12\x34\n\x07updates\x18\x03 \x03(\x0b\x32#.swimprotocol.grpc.proto.SwimUpdate*%\n\nSwimStatus\x12\x0b\n\x07OFFLINE\x10\x00\x12\n\n\x06ONLINE\x10\x01\x32\x86\x02\n\x0cSwimProtocol\x12M\n\x04Ping\x12!.swimprotocol.grpc.proto.SwimPing\x1a .swimprotocol.grpc.proto.SwimAck\"\x00\x12S\n\x07PingReq\x12$.swimprotocol.grpc.proto.SwimPingReq\x1a .swimprotocol.grpc.proto.SwimAck\"\x00\x12R\n\x04Sync\x12#.swimprotocol.grpc.proto.SwimGossip\x1a#.swimprotocol.grpc.proto.SwimGossip\"\x00\x62\x06proto3'
)

_SWIMSTATUS = _descriptor.EnumDescriptor(
  name='SwimStatus',
  full_name='swimprotocol.grpc.proto.SwimStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ONLINE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=484,
  serialized_end=521,
)
_sym_db.RegisterEnumDescriptor(_SWIMSTATUS)

SwimStatus = enum_type_wrapper.EnumTypeWrapper(_SWIMSTATUS)
OFFLINE = 0
ONLINE = 1



_SWIMPING = _descriptor.Descriptor(
  name='SwimPing',
  full_name='swimprotocol.grpc.proto.SwimPing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=81,
)


_SWIMPINGREQ = _descriptor.Descriptor(
  name='SwimPingReq',
  full_name='swimprotocol.grpc.proto.SwimPingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='swimprotocol.grpc.proto.SwimPingReq.target', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=112,
)


_SWIMACK = _descriptor.Descriptor(
  name='SwimAck',
  full_name='swimprotocol.grpc.proto.SwimAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='online', full_name='swimprotocol.grpc.proto.SwimAck.online', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=139,
)


_SWIMUPDATE_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='swimprotocol.grpc.proto.SwimUpdate.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='swimprotocol.grpc.proto.SwimUpdate.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='swimprotocol.grpc.proto.SwimUpdate.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=362,
)

_SWIMUPDATE = _descriptor.Descriptor(
  name='SwimUpdate',
  full_name='swimprotocol.grpc.proto.SwimUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='swimprotocol.grpc.proto.SwimUpdate.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='modified', full_name='swimprotocol.grpc.proto.SwimUpdate.modified', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='swimprotocol.grpc.proto.SwimUpdate.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='swimprotocol.grpc.proto.SwimUpdate.metadata', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SWIMUPDATE_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_modified', full_name='swimprotocol.grpc.proto.SwimUpdate.optional_modified',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=142,
  serialized_end=383,
)


_SWIMGOSSIP = _descriptor.Descriptor(
  name='SwimGossip',
  full_name='swimprotocol.grpc.proto.SwimGossip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='swimprotocol.grpc.proto.SwimGossip.source', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='swimprotocol.grpc.proto.SwimGossip.clock', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updates', full_name='swimprotocol.grpc.proto.SwimGossip.updates', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=482,
)

_SWIMUPDATE_METADATAENTRY.containing_type = _SWIMUPDATE
_SWIMUPDATE.fields_by_name['status'].enum_type = _SWIMSTATUS
_SWIMUPDATE.fields_by_name['metadata'].message_type = _SWIMUPDATE_METADATAENTRY
_SWIMUPDATE.oneofs_by_name['optional_modified'].fields.append(
  _SWIMUPDATE.fields_by_name['modified'])
_SWIMUPDATE.fields_by_name['modified'].containing_oneof = _SWIMUPDATE.oneofs_by_name['optional_modified']
_SWIMGOSSIP.fields_by_name['updates'].message_type = _SWIMUPDATE
DESCRIPTOR.message_types_by_name['SwimPing'] = _SWIMPING
DESCRIPTOR.message_types_by_name['SwimPingReq'] = _SWIMPINGREQ
DESCRIPTOR.message_types_by_name['SwimAck'] = _SWIMACK
DESCRIPTOR.message_types_by_name['SwimUpdate'] = _SWIMUPDATE
DESCRIPTOR.message_types_by_name['SwimGossip'] = _SWIMGOSSIP
DESCRIPTOR.enum_types_by_name['SwimStatus'] = _SWIMSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwimPing = _reflection.GeneratedProtocolMessageType('SwimPing', (_message.Message,), {
  'DESCRIPTOR' : _SWIMPING,
  '__module__' : 'swimprotocol.grpc.proto.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.proto.SwimPing)
  })
_sym_db.RegisterMessage(SwimPing)

SwimPingReq = _reflection.GeneratedProtocolMessageType('SwimPingReq', (_message.Message,), {
  'DESCRIPTOR' : _SWIMPINGREQ,
  '__module__' : 'swimprotocol.grpc.proto.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.proto.SwimPingReq)
  })
_sym_db.RegisterMessage(SwimPingReq)

SwimAck = _reflection.GeneratedProtocolMessageType('SwimAck', (_message.Message,), {
  'DESCRIPTOR' : _SWIMACK,
  '__module__' : 'swimprotocol.grpc.proto.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.proto.SwimAck)
  })
_sym_db.RegisterMessage(SwimAck)

SwimUpdate = _reflection.GeneratedProtocolMessageType('SwimUpdate', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _SWIMUPDATE_METADATAENTRY,
    '__module__' : 'swimprotocol.grpc.proto.swimprotocol_pb2'
    # @@protoc_insertion_point(class_scope:swimprotocol.grpc.proto.SwimUpdate.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _SWIMUPDATE,
  '__module__' : 'swimprotocol.grpc.proto.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.proto.SwimUpdate)
  })
_sym_db.RegisterMessage(SwimUpdate)
_sym_db.RegisterMessage(SwimUpdate.MetadataEntry)

SwimGossip = _reflection.GeneratedProtocolMessageType('SwimGossip', (_message.Message,), {
  'DESCRIPTOR' : _SWIMGOSSIP,
  '__module__' : 'swimprotocol.grpc.proto.swimprotocol_pb2'
  # @@protoc_insertion_point(class_scope:swimprotocol.grpc.proto.SwimGossip)
  })
_sym_db.RegisterMessage(SwimGossip)


_SWIMUPDATE_METADATAENTRY._options = None

_SWIMPROTOCOL = _descriptor.ServiceDescriptor(
  name='SwimProtocol',
  full_name='swimprotocol.grpc.proto.SwimProtocol',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=524,
  serialized_end=786,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='swimprotocol.grpc.proto.SwimProtocol.Ping',
    index=0,
    containing_service=None,
    input_type=_SWIMPING,
    output_type=_SWIMACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PingReq',
    full_name='swimprotocol.grpc.proto.SwimProtocol.PingReq',
    index=1,
    containing_service=None,
    input_type=_SWIMPINGREQ,
    output_type=_SWIMACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Sync',
    full_name='swimprotocol.grpc.proto.SwimProtocol.Sync',
    index=2,
    containing_service=None,
    input_type=_SWIMGOSSIP,
    output_type=_SWIMGOSSIP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SWIMPROTOCOL)

DESCRIPTOR.services_by_name['SwimProtocol'] = _SWIMPROTOCOL

# @@protoc_insertion_point(module_scope)
